[2023-05-26T19:42:14.058+0400] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summary.speech_to_text manual__2023-05-26T15:41:46.889732+00:00 [queued]>
[2023-05-26T19:42:14.074+0400] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summary.speech_to_text manual__2023-05-26T15:41:46.889732+00:00 [queued]>
[2023-05-26T19:42:14.075+0400] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-26T19:42:14.110+0400] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): speech_to_text> on 2023-05-26 15:41:46.889732+00:00
[2023-05-26T19:42:14.162+0400] {standard_task_runner.py:57} INFO - Started process 923 to run task
[2023-05-26T19:42:14.182+0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'podcast_summary', 'speech_to_text', 'manual__2023-05-26T15:41:46.889732+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summary.py', '--cfg-path', '/tmp/tmp25_e590b']
[2023-05-26T19:42:14.193+0400] {standard_task_runner.py:85} INFO - Job 102: Subtask speech_to_text
[2023-05-26T19:42:14.253+0400] {cli_action_loggers.py:135} WARNING - Failed to log action (sqlite3.OperationalError) disk I/O error
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-05-26T19:42:14.357+0400] {task_command.py:410} INFO - Running <TaskInstance: podcast_summary.speech_to_text manual__2023-05-26T15:41:46.889732+00:00 [running]> on host DESKTOP-V010GL9.localdomain
[2023-05-26T19:42:14.543+0400] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='podcast_summary' AIRFLOW_CTX_TASK_ID='speech_to_text' AIRFLOW_CTX_EXECUTION_DATE='2023-05-26T15:41:46.889732+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-26T15:41:46.889732+00:00'
[2023-05-26T19:42:14.560+0400] {base.py:73} INFO - Using connection ID 'podcasts' for task execution.
[2023-05-26T19:42:16.567+0400] {logging_mixin.py:149} INFO - Transcribing what-you-miss-when-you-miss-watercooler-conversations.mp3
[2023-05-26T19:42:16.577+0400] {logging_mixin.py:149} WARNING - /home/chinnu/.local/lib/python3.10/site-packages/pydub/utils.py:198 RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
[2023-05-26T19:42:16.582+0400] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/chinnu/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/chinnu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/chinnu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/chinnu/airflow/dags/podcast_summary.py", line 98, in speech_to_text
    mp3 = AudioSegment.from_mp3(filepath)
  File "/home/chinnu/.local/lib/python3.10/site-packages/pydub/audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "/home/chinnu/.local/lib/python3.10/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/home/chinnu/.local/lib/python3.10/site-packages/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
[2023-05-26T19:42:16.588+0400] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=podcast_summary, task_id=speech_to_text, execution_date=20230526T154146, start_date=20230526T154214, end_date=20230526T154216
[2023-05-26T19:42:16.606+0400] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task speech_to_text ([Errno 2] No such file or directory: 'ffprobe'; 923)
[2023-05-26T19:42:16.637+0400] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-26T19:42:16.664+0400] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
